import './globals.css'
import {MyThemeProvider} from '../../styles/MyThemeProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <MyThemeProvider>{children}</MyThemeProvider>
        </body>
    </html>
  )
}
